version: '3'

services:
  zoom-integration:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./recordings:/app/recordings
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn zoom_integration:app --host 0.0.0.0 --port 8000 --reload
